version: 1.0.{build}

install:
    - nuget restore

build:
  project: ExchangeMatchingEngine.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 5qFuQ+SuUfX92oJp9MzFTTq1amkw8LjZV9iTojsHeHH6tdTvN9kJLZqBr1CWEKzQ

after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:EME.Tests/bin/debug/EME.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml --full-sources